FROM openjdk:17
ADD target/DS_2022_30244_Zilai_Denis_Assignment_2.jar DS_2022_30244_Zilai_Denis_Assignment_2.jar
EXPOSE 8080:8080
ENTRYPOINT ["java", "-jar", "DS_2022_30244_Zilai_Denis_Assignment_2.jar"]